import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

// Blog cornerstone pages (CMO deliverable C2) live as Markdown in src/content/blog/.
// Drop a new .md file in with this frontmatter and it appears on /blog automatically.
const blog = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/blog' }),
  schema: z.object({
    title: z.string(),
    description: z.string(),
    pubDate: z.coerce.date(),
    draft: z.boolean().default(false),
    // Marks template/seed content not yet supplied by CMO C2.
    placeholder: z.boolean().default(false),
    // Optional FAQ Q&A pairs (ARY-470). When present, the post emits FAQPage
    // JSON-LD (in addition to BlogPosting) so its "Frequently asked questions"
    // block is eligible for the FAQ rich result. Mirror the on-page Q&As here.
    faqs: z
      .array(z.object({ question: z.string(), answer: z.string() }))
      .optional(),
  }),
});

// Localized cornerstone articles (ARY-523). Machine-translated overlays of the
// English `blog` posts, one Markdown file per locale under
// `src/content/blog-i18n/<locale>/<translated-slug>.md`. Kept in a SEPARATE
// collection (not under src/content/blog/) so the English glob above never
// picks them up and English `/blog/<slug>/` URLs stay byte-for-byte unchanged.
// `ref` ties each back to its English canonical id; `locale`/`slug` drive the
// locale-prefixed route, hreflang alternates, and the language switcher. Files
// + the src/i18n/blog-slugs.json manifest are regenerated by
// `node scripts/translate.mjs --group=blog`.
const blogI18n = defineCollection({
  // `generateId` from the file PATH (`<locale>/<slug>`) is required: the glob
  // loader otherwise defaults the id to the frontmatter `slug`, and non-Latin
  // locales share the English slug — so their entries would collide to a single
  // id and all but one locale would silently drop out of the build (ARY-523).
  loader: glob({
    pattern: '**/*.md',
    base: './src/content/blog-i18n',
    generateId: ({ entry }) => entry.replace(/\.md$/, ''),
  }),
  schema: z.object({
    title: z.string(),
    description: z.string(),
    pubDate: z.coerce.date(),
    ref: z.string(),
    locale: z.string(),
    slug: z.string(),
    draft: z.boolean().default(false),
    placeholder: z.boolean().default(false),
    faqs: z
      .array(z.object({ question: z.string(), answer: z.string() }))
      .optional(),
  }),
});

export const collections = { blog, blogI18n };
